site_name: Devops Journey Docs
nav: 
  - Home: index.md
  - Cloud:
    - AWS: 
      - Index: cloud/aws/index.md
  - Kubernetes:
    - Index: kubernetes/index.md 
  - Pipelines:
    - Index: pipelines/index.md
theme:
  name: readthedocs
  palette:
    primary: 'indigo'
    accent: 'pink'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'